export TEMPORAL_ADDRESS=${TEMPORAL_FRONTEND_HOST:-$RENDER_SERVICE_NAME}:7233
# Temporary compatibility alias; can be removed once all tooling uses TEMPORAL_ADDRESS.
export TEMPORAL_CLI_ADDRESS=${TEMPORAL_CLI_ADDRESS:-$TEMPORAL_ADDRESS}
